[2024-11-29T04:00:56.083+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-29T04:00:56.107+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_games_etl_daily.load_data scheduled__2024-11-27T02:30:00+00:00 [queued]>
[2024-11-29T04:00:56.113+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_games_etl_daily.load_data scheduled__2024-11-27T02:30:00+00:00 [queued]>
[2024-11-29T04:00:56.114+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-29T04:00:56.140+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_data> on 2024-11-27 02:30:00+00:00
[2024-11-29T04:00:56.148+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_games_etl_daily', 'load_data', 'scheduled__2024-11-27T02:30:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/daily_data_etl.py', '--cfg-path', '/tmp/tmpyzp8e4vp']
[2024-11-29T04:00:56.149+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=273) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-29T04:00:56.150+0000] {standard_task_runner.py:91} INFO - Job 57: Subtask load_data
[2024-11-29T04:00:56.150+0000] {standard_task_runner.py:63} INFO - Started process 287 to run task
[2024-11-29T04:00:56.213+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_games_etl_daily.load_data scheduled__2024-11-27T02:30:00+00:00 [running]> on host 105fc369984c
[2024-11-29T04:00:56.301+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_games_etl_daily' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-27T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-27T02:30:00+00:00'
[2024-11-29T04:00:56.302+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-29T04:00:56.564+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-29T04:00:56.930+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-29T04:01:01.045+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-29T04:01:01.045+0000] {logging_mixin.py:188} INFO - An error occurred: 002003 (42S02): 01b8aff1-0004-3865-0002-58cf000308da: SQL compilation error:
Table 'NBA_GAMES_STAGING' does not exist or not authorized.
[2024-11-29T04:01:01.046+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-29T04:01:01.046+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/daily_data_etl.py", line 162, in load_data
    raise e
  File "/opt/airflow/dags/daily_data_etl.py", line 130, in load_data
    cursor.execute(insert_query, (
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (42S02): 01b8aff1-0004-3865-0002-58cf000308da: SQL compilation error:
Table 'NBA_GAMES_STAGING' does not exist or not authorized.
[2024-11-29T04:01:01.054+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_games_etl_daily, task_id=load_data, run_id=scheduled__2024-11-27T02:30:00+00:00, execution_date=20241127T023000, start_date=20241129T040056, end_date=20241129T040101
[2024-11-29T04:01:01.067+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 57 for task load_data (002003 (42S02): 01b8aff1-0004-3865-0002-58cf000308da: SQL compilation error:
Table 'NBA_GAMES_STAGING' does not exist or not authorized.; 287)
[2024-11-29T04:01:01.099+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-29T04:01:01.111+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-29T04:01:01.114+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
