[2024-11-27T19:28:06.172+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-27T19:28:06.205+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_games_etl_daily.extract_data scheduled__2024-11-25T02:30:00+00:00 [queued]>
[2024-11-27T19:28:06.215+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_games_etl_daily.extract_data scheduled__2024-11-25T02:30:00+00:00 [queued]>
[2024-11-27T19:28:06.216+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-27T19:28:06.229+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract_data> on 2024-11-25 02:30:00+00:00
[2024-11-27T19:28:06.241+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_games_etl_daily', 'extract_data', 'scheduled__2024-11-25T02:30:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/daily_data_etl.py', '--cfg-path', '/tmp/tmpl2fr3dmy']
[2024-11-27T19:28:06.245+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask extract_data
[2024-11-27T19:28:06.247+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=217) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-27T19:28:06.249+0000] {standard_task_runner.py:63} INFO - Started process 252 to run task
[2024-11-27T19:28:06.308+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_games_etl_daily.extract_data scheduled__2024-11-25T02:30:00+00:00 [running]> on host 105fc369984c
[2024-11-27T19:28:06.396+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_games_etl_daily' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T02:30:00+00:00'
[2024-11-27T19:28:06.397+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-27T19:28:06.398+0000] {logging_mixin.py:188} INFO - Logical date: 2024-11-25 02:30:00+00:00
[2024-11-27T19:28:06.398+0000] {logging_mixin.py:188} INFO - Previous day date: 2024-11-24
[2024-11-27T19:28:07.044+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-27T19:28:07.045+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/daily_data_etl.py", line 49, in extract_data
    raise Exception(f'Request failed with status code {response.status_code}')
Exception: Request failed with status code 429
[2024-11-27T19:28:07.057+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_games_etl_daily, task_id=extract_data, run_id=scheduled__2024-11-25T02:30:00+00:00, execution_date=20241125T023000, start_date=20241127T192806, end_date=20241127T192807
[2024-11-27T19:28:07.069+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 38 for task extract_data (Request failed with status code 429; 252)
[2024-11-27T19:28:07.106+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-27T19:28:07.118+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
