[2024-11-24T19:47:38.240+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-24T19:47:38.263+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_games_etl.stage_file_to_snowflake manual__2024-11-24T19:47:35.773370+00:00 [queued]>
[2024-11-24T19:47:38.269+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_games_etl.stage_file_to_snowflake manual__2024-11-24T19:47:35.773370+00:00 [queued]>
[2024-11-24T19:47:38.269+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-24T19:47:38.279+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): stage_file_to_snowflake> on 2024-11-24 19:47:35.773370+00:00
[2024-11-24T19:47:38.285+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_games_etl', 'stage_file_to_snowflake', 'manual__2024-11-24T19:47:35.773370+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/historical_data_etl.py', '--cfg-path', '/tmp/tmpq8ms8sx6']
[2024-11-24T19:47:38.286+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask stage_file_to_snowflake
[2024-11-24T19:47:38.288+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=415) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-24T19:47:38.289+0000] {standard_task_runner.py:63} INFO - Started process 418 to run task
[2024-11-24T19:47:38.318+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_games_etl.stage_file_to_snowflake manual__2024-11-24T19:47:35.773370+00:00 [running]> on host 98bc2e09bbb2
[2024-11-24T19:47:38.372+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_games_etl' AIRFLOW_CTX_TASK_ID='stage_file_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2024-11-24T19:47:35.773370+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-24T19:47:35.773370+00:00'
[2024-11-24T19:47:38.373+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-24T19:47:38.373+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-24T19:47:38.374+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 233, in execute
    self.op_kwargs = self.determine_kwargs(context)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 244, in determine_kwargs
    return KeywordParameters.determine(self.python_callable, self.op_args, context).unpacking()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 163, in determine
    raise ValueError(f"The key {name!r} in args is a part of kwargs and therefore reserved.")
ValueError: The key 'conn' in args is a part of kwargs and therefore reserved.
[2024-11-24T19:47:38.380+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_games_etl, task_id=stage_file_to_snowflake, run_id=manual__2024-11-24T19:47:35.773370+00:00, execution_date=20241124T194735, start_date=20241124T194738, end_date=20241124T194738
[2024-11-24T19:47:38.389+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task stage_file_to_snowflake (The key 'conn' in args is a part of kwargs and therefore reserved.; 418)
[2024-11-24T19:47:38.422+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-24T19:47:38.429+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
